version: "3"
services:
    vllm-openai:
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities:
                              - gpu
        volumes:
            - ~/.cache/huggingface:/root/.cache/huggingface
            - ./models:/models
        environment:
            - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}
        ports:
            - "${PORT}:8000"
        ipc: host
        image: vllm/vllm-openai:latest
        command: --trust-remote-code --model allenai/Molmo-7B-D-0924
